<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>UBCMS Demo Site</title>
    <link rel="stylesheet" href="//www.buffalo.edu/etc/designs/ubcms/clientlibs.min.css" type="text/css">
    <link rel="stylesheet" href="//www.buffalo.edu/etc/designs/ubcms/clientlibs-rwd.min.css" type="text/css">
    <link rel="stylesheet" href="css/main.css" type="text/css">
    <script type="text/javascript" src="//www.buffalo.edu/etc/designs/ubcms/clientlibs.min.js"></script>
    <script type="text/javascript" src="//www.buffalo.edu/etc/designs/ubcms/clientlibs-rwd.min.js"></script>
</head>
<body class="page contentpage">
    <div class="outerheader ubheader">
        <div class="inner">
            <a class="ublogo" href="http://www.buffalo.edu/"><img src="//www.buffalo.edu/etc/designs/ubcms/images/ubheader/ub-logo.png" width="360" height="35" alt="University at Buffalo, The State University of New York"></a>
            <a class="reachingothers" href="http://www.buffalo.edu/"><img src="//www.buffalo.edu/etc/designs/ubcms/images/ubheader/reaching-others.gif" width="115" height="35" alt="Reaching Others"></a>
            <img class="print" src="//www.buffalo.edu/etc/designs/ubcms/images/ubheader/ub-logo-print.gif" width="450" height="22" alt="University at Buffalo - The State University of New York">
        </div>
    </div>
    <div id="page"><div class="page-inner"><div class="page-inner-1"><div class="page-inner-2"><div class="page-inner-2a"></div><div class="page-inner-3">
        <div class="innerheader"><? include "ubcms/header.html" ?></div>
        <div id="columns" class="one-column clearfix"><div class="columns-bg columns-bg-1"><div class="columns-bg columns-bg-2"><div class="columns-bg columns-bg-3"><div class="columns-bg columns-bg-4"><div id="center">
